<?php

defined("ISLANDORA_COLLECTION_TOGGLE_PUBLISH_ADMINISTER_UNPUBLISHED") ? NULL : define("ISLANDORA_COLLECTION_TOGGLE_PUBLISH_ADMINISTER_UNPUBLISHED", 'Administer published/unpublished collection setting.');

/**
 * Implements hook_permission().
 */
function islandora_collection_toggle_publish_permission() {
  return array(
    ISLANDORA_COLLECTION_TOGGLE_PUBLISH_ADMINISTER_UNPUBLISHED => array(
      'title' => t('Administer unpublished collection setting.'),
      'description' => t("Administer unpublished collection setting"),
    ),
  );
}


/**
 * Implements hook_menu().
 */
function islandora_collection_toggle_publish_menu() {
  return array(
    'admin/islandora/tools/collection_toggle_publish' => array(
      'title' => 'Islandora Collection Toggle Publish',
      'description' => 'Default publication settings for collections.',
      'type' => MENU_NORMAL_ITEM,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_collection_toggle_publish_settings_form'),
      'file' => 'includes/forms.inc',
      'access arguments' => array(ISLANDORA_COLLECTION_TOGGLE_PUBLISH_ADMINISTER_DEFAULTS),
    ),
  );
}

/**
 * Implements hook_form_islandora_object_properties_form_alter().
 */
function islandora_collection_toggle_publish_form_islandora_object_properties_form_alter(array &$form, array &$form_state) {
  module_load_include('inc', 'islandora_collection_toggle_publish', 'includes/utilities');
  $form['islandora_collection_toggle_publish_is_published'] = array(
    '#type' => 'checkbox',
    '#title' => 'Publish',
    '#description' => t('Check this to make the collection available to the public.'),
    '#default_value' => islandora_collection_toggle_publish_collection_is_published($form['pid']['#value']) ? TRUE : FALSE,
  );
  array_unshift($form['#submit'], 'islandora_collection_toggle_publish_properties');
}

/**
 * Implements hook_islandora_object_access().
 *
 * Checks for an IP address embargo and handles redirects if necessary.
 */
function islandora_collection_toggle_publish_islandora_object_access($op, $islandora_object, $user) {
  module_load_include('inc', 'islandora_collection_toggle_publish', 'includes/utilities');
  $relationships = $islandora_object->relationships->get();
  if (is_collection($islandora_object)) {
    $pid = $islandora_object->id;
  }
  else {
    $pid = get_parent_collection($islandora_object);
  }
  return islandora_collection_toggle_publish_collection_is_published($pid) || user_access(ISLANDORA_COLLECTION_TOGGLE_PUBLISH_ADMINISTER_UNPUBLISHED) ? NULL : FALSE;
}

/**
 * Implements hook_islandora_object_access().
 *
 * Checks for an IP address embargo and handles redirects if necessary.
 */
function islandora_collection_toggle_publish_islandora_datastream_access($op, $islandora_ds, $user) {
  module_load_include('inc', 'islandora_collection_toggle_publish', 'includes/utilities');
  if (is_collection($islandora_ds->parent)) {
    $pid = $islandora_ds->parent->id;
  }
  else {
    $pid = get_parent_collection($islandora_ds->parent);
  }
  return islandora_collection_toggle_publish_collection_is_published($pid) || user_access(ISLANDORA_COLLECTION_TOGGLE_PUBLISH_ADMINISTER_UNPUBLISHED) ? NULL : FALSE;
}

function islandora_collection_toggle_publish_islandora_object_ingested($islandora_object) {
  module_load_include('inc', 'islandora_collection_toggle_publish', 'includes/utilities');  
  if (!variable_get('islandora_collection_toggle_publish_by_default', TRUE)){
    islandora_collection_toggle_publish_unpublish_collection($islandora_object->id);
  }
}