<?php

defined("ISLANDORA_COLLECTION_TOGGLE_PUBLISH_ADMINISTER_UNPUBLISHED") ? NULL : define("ISLANDORA_COLLECTION_TOGGLE_PUBLISH_ADMINISTER_UNPUBLISHED", 'Administer published/unpublished collection setting.');
defined("ISLANDORA_COLLECTION_TOGGLE_PUBLISH_ADMINISTER_DEFAULTS") ? NULL : define("ISLANDORA_COLLECTION_TOGGLE_PUBLISH_ADMINISTER_DEFAULTS", 'administer publish toggle defaults');

/**
 * Implements hook_permission().
 */
function islandora_collection_toggle_publish_permission() {
  return array(
    ISLANDORA_COLLECTION_TOGGLE_PUBLISH_ADMINISTER_UNPUBLISHED => array(
      'title' => t('Administer unpublished collection setting.'),
      'description' => t("Administer unpublished collection setting"),
    ),
    ISLANDORA_COLLECTION_TOGGLE_PUBLISH_ADMINISTER_DEFAULTS => array(
      'title' => t('administer publish toggle defaults'),
      'description' => t("administer publish toggle defaults"),
    ),
  );
}


/**
 * Implements hook_menu().
 */
function islandora_collection_toggle_publish_menu() {
  return array(
    'admin/islandora/tools/collection_toggle_publish' => array(
      'title' => 'Islandora Collection Toggle Publish',
      'description' => 'Default publication settings for collections.',
      'type' => MENU_NORMAL_ITEM,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_collection_toggle_publish_settings_form'),
      'file' => 'includes/forms.inc',
      'access arguments' => array(ISLANDORA_COLLECTION_TOGGLE_PUBLISH_ADMINISTER_DEFAULTS),
    ),
  );
}

/**
 * Implements hook_form_islandora_object_properties_form_alter().
 */
 function islandora_collection_toggle_publish_form_islandora_object_properties_form_alter(array &$form, array &$form_state) {
   $obj = islandora_object_load($form['pid']['#value']);
   $models = $obj->models;
   if (in_array('islandora:collectionCModel', $models)) {
     module_load_include('inc', 'islandora_collection_toggle_publish', 'includes/utilities');
     $form['islandora_collection_toggle_publish_is_published'] = array(
       '#type' => 'checkbox',
       '#title' => 'Publish',
       '#description' => t('Check this to make the collection available to the public.'),
       '#default_value' => islandora_collection_toggle_publish_collection_is_published($form['pid']['#value']) ? TRUE : FALSE,
     );
     array_unshift($form['#submit'], 'islandora_collection_toggle_publish_properties');
   }
 }

/**
 * Implements hook_islandora_object_access().
 *
 */
function islandora_collection_toggle_publish_islandora_object_access($op, $islandora_object, $user) {
  return grant_access($islandora_object);
}

/**
 * Implements hook_islandora_object_access().
 *
 */
function islandora_collection_toggle_publish_islandora_datastream_access($op, $islandora_ds, $user) {
  if($islandora_ds->id == 'JP2') return TRUE;
  return grant_access($islandora_ds->parent);
}

function grant_access($islandora_object) {
  module_load_include('inc', 'islandora_collection_toggle_publish', 'includes/utilities');
  $djip = variable_get('islandora_ip_embargo_djatoka_public_ip_address', '127.0.0.1');
  if (ip_address() == $djip) {
    return TRUE;
  }
  if (is_collection($islandora_object)) {
    $pid = $islandora_object->id;
  }
  else {
    $pid = get_parent_collection($islandora_object);
  }
  $published = islandora_collection_toggle_publish_collection_is_published($pid);
  $has_permission = user_access(ISLANDORA_COLLECTION_TOGGLE_PUBLISH_ADMINISTER_UNPUBLISHED);
  $access = ($published || $has_permission) ? TRUE : FALSE;

  return $access;
}

function islandora_collection_toggle_publish_islandora_object_ingested($islandora_object) {
  module_load_include('inc', 'islandora_collection_toggle_publish', 'includes/utilities');
  if (!variable_get('islandora_collection_toggle_publish_by_default', TRUE)){
    islandora_collection_toggle_publish_unpublish_collection($islandora_object->id);
    $multisites = variable_get('islandora_collection_toggle_publish_multisites_to_update','');
    if (!empty($multisites)) {
      foreach (explode(',', $multisites) as $site) {
	$drupal_root = DRUPAL_ROOT;
	$pid         = $islandora_object->id;
        $op          = $submitted ? 'publish' : 'unpublish';
        $command     = "cd $drupal_root/sites/$site && drush ict-pub $op --pid=$pid";
        exec($command);
      }
    }
  }
}

function islandora_collection_toggle_publish_islandora_solr_results_alter(&$search_results) {
  module_load_include('inc', 'islandora_collection_toggle_publish', 'includes/utilities');
  $found_pids = array();
  $publish = array();
  $unpub_array = array();
  foreach ($search_results as $key => $value) {
    if (!is_collection(islandora_object_load($value['PID']))) {
      $check = get_parent_collection(islandora_object_load($value['PID']));
    }
     $not_pub = !islandora_collection_toggle_publish_collection_is_published($value['PID']);
     $not_pub_parent = !islandora_collection_toggle_publish_collection_is_published($check);
    if ($not_pub || $not_pub_parent) {
      $search_results[$key]['thumbnail_url'] = "/islandora/object/islandora%3Aroot/datastream/TN/view";
      $search_results[$key]['solr_doc'] = array();
      $search_results[$key]['solr_doc']['dc.title'] ='Object is currently unpublished.';
      if (isset($search_results[$key]['solr_doc'])) {
        // dpm($search_results[$key]['solr_doc']);
        // dpm($search_results[$key]['solr_doc']);
        // return;
      }
      // dpm($search_results[$key]);
      // return;

      $search_results[$key]['object_url'] = '';
      $search_results[$key]['object_label'] = 'This object is unpublished';
      $search_results[$key]['unpublished'] = TRUE;
    }
  }
}


function islandora_collection_toggle_publish_theme_registry_alter(&$theme_registry) {
  $path = drupal_get_path('module','islandora_collection_toggle_publish');
  $template_files = drupal_find_theme_templates($theme_registry, '.tpl.php', $path);
  foreach ($template_files as $key => $file) {
    $theme_registry[$key]['theme path']= $path;
    $theme_registry[$key] = array_merge($theme_registry[$key], $file);
  }
}
